### ISSUE TITLE
Complete React Routing

### ISSUE THREAD

**Issue by 1298se** [1298se/Contrail-Web#20]
Complete Routing as follows:

- When user enters '/', if the user is logged in, he is redirect to '/app/files'
- When user enters '/', if the user is not logged in, he is redirected to '/auth'

Ensure the user cannot access '/app' without logging in!

EXTREMELY USEFUL LINK: https://css-tricks.com/react-router-4/?fbclid=IwAR0cL1etRcnn_m80hE-_q8ola5MKIMYLHKjMTTzEniBSU3bRRhZY_b1zXLE

**Comment by notoriousmango** [comment]
Closed

**Comment by notoriousmango** [comment]
@virajg224 why would you reopen this

**Comment by virajg224** [comment]
@notoriousmango We are using react router for the front-end app

**Comment by notoriousmango** [comment]
@virajg224 isn't this done already?

**Comment by virajg224** [comment]
Its sort of done but I need to add authorization redirect to it so if a user accesses /app/files, etc they are redirected back
