### ISSUE TITLE
Change routing on Express Server

### ISSUE THREAD

**Issue by 1298se** [1298se/Contrail-Web#27]
Since we are rendering all front-end displays through React, we only need to received data from the Server. 

Task:
- change path from "/login" to "/api/login". It should not send any files, just status 200 alongside code "userLoginSuccessful"
- repeat for "/register"

**Comment by dave2000sang** [comment]
> Since we are rendering all front-end displays through React, we only need to received data from the Server.
> 
> Task:
> 
> * change path from "/login" to "/api/login". It should not send any files, just status 200 alongside code "userLoginSuccessful"
> * repeat for "/register"

for login and registration fail, send "userLoginFailed" and "userRegistrationFailed" with status 200

**Comment by 1298se** [comment]
The response status and code should depend on what the error is. So, if its a Firebase error, it should be different than if its a communication error between our own frontend and backend
