### ISSUE TITLE
 Display name not showing up

### ISSUE THREAD

**Issue by virajg224** [1298se/Contrail-Web#58]
When the user data is returned in the loginUser function, we see displayName as null. 
![Capture](https://user-images.githubusercontent.com/25271362/60273583-71b1cb00-98c4-11e9-988b-d088dbafbdef.PNG)

**Comment by notoriousmango** [comment]
This is because we don't update the name when we create the user.

**Comment by notoriousmango** [comment]
@1298se We can update the name when we create instead of storing it to db
